### ISSUE TITLE
Image is cutoff / cropped

### ISSUE THREAD

**Issue by jdonofrio728** [jtheoof/swappy#6]
I've recently discovered this tool and implemented it into my daily workflow. However for some reason the images when copied to clipboard or saved are cut off or zoomed in. Here is an example

This picture is a screen shot straight from grim into wl-copy
![image](https://user-images.githubusercontent.com/10515329/73199120-41eccf00-4102-11ea-9c57-840cc18d48dd.png)

This is the "same" screen shot which goes into swappy then into my clipboard:
![image](https://user-images.githubusercontent.com/10515329/73199188-5cbf4380-4102-11ea-97ad-bfde48343408.png)

I'm running sway 1.0 with wlroots 0.10.0 (latest on arch)

Let me know if there is anything else that you may need to debug!

**Comment by jtheoof** [comment]
@jdonofrio728 it seems you are using the `-g` option of swappy which is not as solid as its `grim` counterpart. It needs more love. Can you try the `-f` option and use swappy as a pipe from `grim` output (See README).

Let me know if it fixes the issue for you.

**Comment by jdonofrio728** [comment]
Hey thanks for the response. The actual command that is being executed by sway is
`grim -g "$(slurp)" - | swappy -f -`

This is the first example from the README. So the -g option from swappy is not in play here. Something else seems to be problematic :(

**Comment by jtheoof** [comment]
You're right, my bad I read too fast.

Let me see if I can figure out what's going on.

**Comment by jdonofrio728** [comment]
@jtheoof I did a little experiment this morning, and I think the issue might be around the fact that my displays are scaled. I have a 4k display scaled to 2. If I reduce the scaling to 1, then the screen shot copies correctly.

**Comment by jtheoof** [comment]
OK I'm gonna try to reproduce it. How do you scale the display with `sway`?

**Comment by jdonofrio728** [comment]
Grab your outputs by running
`swaymsg -t get_outputs`

Then set the scale by running (eDP-1 is my screen):
`swaymsg output eDP-1 scale 2`

**Comment by jtheoof** [comment]
I have not forgot about you @jdonofrio728.
I can easily reproduce the issue with the scaling config but this fix requires more work than I expected. I need to update the logic when the window is created. And I really have no expertise in GTK land and its layout management. I'll tackle this when I have more free time.

**Comment by jtheoof** [comment]
Hi @jdonofrio728, the issue should now be fixed with latest swappy.

**Comment by maximbaz** [comment]
Hi @jtheoof , I can still reproduce this issue on the latest master. My scale is `2.5`, swappy crops the image when the scale is set to `2` as well, only if I set it to `1` then the image is copied fully.

**Comment by jtheoof** [comment]
@maximbaz Are you using swappy with the `-g` or the `-f` option?

**Comment by maximbaz** [comment]
`swappy -f area.png`, full script [here](https://github.com/maximbaz/dotfiles/blob/master/bin/sway-screenshot-area)

**Comment by maximbaz** [comment]
If you want I can try to get you some debug info from my system, if you want me to try a development branch with a bunch of `printf`s I would be up for that too, whatever helps :)

**Comment by jdonofrio728** [comment]
@jtheoof I can also validate that the issue is not fixed. The preview window shows the screen show correct. But when you copy it to your clipboard and paste it somewhere, it is cropped.

**Comment by jtheoof** [comment]
Oh I see. My bad, I'll reopen this issue.

**Comment by jtheoof** [comment]
@jdonofrio728 @maximbaz I fixed the `pixbuf` issue with scaling. Now the both the rendering and copy/save logic should work no matter the scale. Let me know if you still have issues.

**Comment by maximbaz** [comment]
It works! Thank you so much 🎉

**Comment by jdonofrio728** [comment]
@jtheoof definitely working! Thank you!
